spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imjm
    username: postgres
    password: 0817
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ENC(09sVzBogF2PpwmAPCWIKTopMC3Vw6SGtka+6t7ugKtLVmJlLpcNuBLmidZLuvxRp2UocWP+RED2DWIA9Y3N9JPofEtexkPW69+iDPrrvr52mpDciXZHWag==)
            client-secret: ENC(KhB+BeKxWiw1lSVJyCrBANnNhg6cFI4lHN/Sql5CS7ArBODznDn0K+foxzXvsrH7)
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

app:
  client:
    domain: http://localhost:3000
  admin:
    domain: http://localhost:3030
  server:
    domain: http://localhost:8080
